### ISSUE TITLE
critical bug with machines

### ISSUE THREAD

**Issue by denden1088** [PixliesEarth/PixliesNet#11]
Pressing the cancel button with any machine with a shared GUI with buttons will sometimes give a player a barrier block. details below

**Comment by denden1088** [comment]
when 2 people are using a forge pressing the cancel button will generate a 2nd placeable barrier block
![image](https://user-images.githubusercontent.com/72841410/101302746-734a2700-380a-11eb-85c3-1d8b79c3af36.png)
![image](https://user-images.githubusercontent.com/72841410/101302757-79d89e80-380a-11eb-831b-5182035c50aa.png)

**Comment by BradBot1** [comment]
Damn it should close the gui for them, that’s really odd. I’ll have a look into it later today
