### ISSUE TITLE
Item bug in /machine menu

### ISSUE THREAD

**Issue by denden1088** [PixliesEarth/PixliesNet#2]
Description: When clicking the close button of the remote interactor in the machine menu it gives the ender pearl from the corner of the crafting recipe to the user (not a visual glitch, the ender pearl is usable)
Image:

![image](https://user-images.githubusercontent.com/72841410/101286736-3b1af800-37ba-11eb-83d2-3119f96b4c80.png)

Recreation:
1. Open the machines menu and click on the remote interactor in items
2. Press the close button

**Comment by amxrmxhdx** [comment]
Thank you very much, this issue has been resolved, and will be eventually fixed once we restart the server.
