### ISSUE TITLE
/n merge has some problems

### ISSUE THREAD

**Issue by Didas7** [PixliesEarth/PixliesNet#21]
![image](https://user-images.githubusercontent.com/75585724/101481657-6b46d000-394d-11eb-88c0-0480f5f79549.png)
![image](https://user-images.githubusercontent.com/75585724/101481942-d395b180-394d-11eb-9d41-232cd026a767.png)

So I merged with Arpinea faction, no claims were tranfered, the pp stayed the same, arpinea was in two factions at the same time, 
the both nation bank didnt merge, and then he tried to unclaim and to disband and it said that he wasn't a member. So the claims are impossible to unclaim.

**Comment by amxrmxhdx** [comment]
Fixed
