### ISSUE TITLE
Plant incubator

### ISSUE THREAD

**Issue by zenakegit** [PixliesEarth/PixliesNet#26]
When placing a stack of seeds in the plant incubator it makes one grow and the rest 63 are just gone

**Comment by BradBot1** [comment]
Hey there! This is a client side bug, they are dropped on the floor, I'll change this so that they go in your inventory in one second!

**Comment by BradBot1** [comment]
Done! It will no longer allow for stacks in that slot, if any other bugs arise open another issue!
