### ISSUE TITLE
Gun & Farming workbenches

### ISSUE THREAD

**Issue by zenakegit** [PixliesEarth/PixliesNet#27]
The gun workbench and the farming workbench has no GUI

**Comment by BradBot1** [comment]
Hey there, to fix this I will need more information then this, can you explain what you mean? Is the inventory blank or does it just not open its inventory when interacted with?

**Comment by zenakegit** [comment]
There is no "gui" like only black stained panes.  supposed to be like the tinker table etc i think

**Comment by BradBot1** [comment]
Oh! This is due to it not having any recipes (that I know of). If it has recipes and they are not loading then re-open this issue.
