### ISSUE TITLE
Can't add settlements

### ISSUE THREAD

**Issue by IAmAze** [PixliesEarth/PixliesNet#34]
I left my old nation and decided to create a new one, I searched for a new spot and set up my base. Now I wanted to add a settlement, but I can't. It just says that I have reached my max possible settlements

**_Screenshots:_**

_1._ https://imgur.com/a/pn2S9wP

_2._ https://imgur.com/a/nEi7f7y

_3._ https://imgur.com/a/L1mgU5l

**Comment by amxrmxhdx** [comment]
Will be fixed next restart
