### ISSUE TITLE
Water Electrolyser not working

### ISSUE THREAD

**Issue by zenakegit** [PixliesEarth/PixliesNet#35]
The Water Electrolyser is not showing the right gui nor working

![2020-12-21_18 25 05](https://user-images.githubusercontent.com/75500268/102804355-f4342180-43b9-11eb-8598-14866717c383.png)

**Comment by BradBot1** [comment]
I just tested this and I could not reproduce this issue? It loaded fine for me. Sometimes the glass panes will not load until energy is received so I will patch that.

**Comment by BradBot1** [comment]
Patched
