### ISSUE TITLE
If you put materials in forge then change recipe, the materials disappear

### ISSUE THREAD

**Issue by dawson612** [PixliesEarth/PixliesNet#37]

**Comment by BradBot1** [comment]
Hey there! Can I get some more information about this issue? You seem to have left your description empty and as a result I am not sure what you are entailing with your report.

**Comment by BradBot1** [comment]
Hey there, you don't seem to be getting back to me. To keep clutter low I will be closing this issue, if you wish to continue this issue feel free to reopen the issue.
