### ISSUE TITLE
You can dupe Wind Turbines

### ISSUE THREAD

**Issue by USmellyBad** [PixliesEarth/PixliesNet#38]
Basically after placing a wind turbine, it doesn't actually remove the one already in you inventory and when you break one it gives you one back. Which has created a very easy way to dupe them. (Just so you know I may or may not have died with a few dupes and someone may or may not have taken them.)

![2020-12-22_19 02 43](https://user-images.githubusercontent.com/76503437/102950848-b3efa480-4488-11eb-803b-25c2c8ae7986.png)
(These have all since been destroyed, this is really the only way I could think of showcasing you could dupe them)

All you need to do to recreate this is:
- 1 Place the Turbine down
- 2 Break It

Wind Turbines also don't actually appear to work properly (Or im just an idiot).

**Comment by BradBot1** [comment]
Should be fixed now! Will be applied in the next patch! Thanks for this issue, and if it persists reopen it!
